HaveIBeenPwned/PwnedPasswordsAzureFunction

- Functions/BlobStorage.cs
More reliable and probably a bit faster
> Use status code instead of message to check if blob was not found

- Functions/BlobStorage.cs
- Functions/Hash.cs
- Functions/PwnedResponse.cs
- Functions/Range.cs
Hi Troy,
This commit has added IntelliSense documentation for the code base, with class, function, function variable and return summaries in Visual Studio. Hopefully this will make understanding the existing codebase a bit quicker for newcomers.
> Documented existing codebase

- .config/dotnet-tools.json
- .editorconfig
- Functions/BlobStorage.cs
- Functions/Hash.cs
- Functions/PwnedResponse.cs
- Functions/Range.cs
- PwnedPasswords.sln
- Added the default [.editorconfig file](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) for .NET.
- Included the **.editorconfig** file as a solution item.
- Added a .NET tool manifest file (**dotnet-tools.json**) with [dotnet-format](https://github.com/dotnet/format) 5.1.225507.
- Ran `dotnet format` to standardize formatting, mostly impacting the number of spaces for a tab (2 to 4).
Inspired by #5.
> Fixing 'Aussie-rules' spacing, take 2

- PwnedPasswords.sln
- README.md
These README updates make things more friendly for cross-platform folks. It builds on #8.
Might need a quick change around the SDK to be used (.NET 3.1 / .NET 5), depending on other open PRs.
> Update README - add JetBrains Rider and Azurite

- .idea/.idea.PwnedPasswords/.idea/.gitignore
- .idea/.idea.PwnedPasswords/.idea/.name
- .idea/.idea.PwnedPasswords/.idea/encodings.xml
- .idea/.idea.PwnedPasswords/.idea/indexLayout.xml
- .idea/.idea.PwnedPasswords/.idea/vcs.xml
- .run/Run functions.run.xml
Extends #22 with a default run configuration for Rider. Totally optional, but a little nice thing.
> Add default Rider run configuration

- Functions/BlobStorage.cs
- Functions/BlobStorageEntry.cs
- Functions/Functions.csproj
- Functions/Range.cs
- Functions/host.json
- README.md
- Tests/Tests.csproj
Bigger PR, sorry for that... Updated the project to make use of Azure Functions v3
* Update to Azure Functions - .NET Core 3.1.
* Update logging to make use of structured logging.
* Inject configuration using `IConfiguration`
* Add null check when no blob was returned from storage.
Make sure to update the configuration when you deploy it: `FUNCTIONS_EXTENSION_VERSION` has to be set to `~3`
**Edit:** Just saw #16 which may make this PR partially obsolete.
> Update to Azure Functions v3

- Functions.Tests/Functions.Tests.csproj
- Functions/Hash.cs
Now we are using .NET 5 (see #27), we can use some of the nice new convienience APIs 👌
> Use .NET APIs to Simplify Hashing Code

- README.md
This PR updates the .net version mentioned in the text to .NET 5.0 and also updates the download link
> Update .NET SDK version and download link in README.md

- Functions.Tests/Functions.Tests.csproj
- Functions.Tests/HashTests.cs
- Functions.Tests/Helpers/TestBindingMetadata.cs
- Functions.Tests/Helpers/TestFunctionContext.cs
- Functions.Tests/Helpers/TestFunctionDefinition.cs
- Functions.Tests/Helpers/TestFunctionInvocation.cs
- Functions.Tests/Helpers/TestHttpRequestData.cs
- Functions.Tests/Helpers/TestHttpResponseData.cs
- Functions.Tests/RangeTests.cs
- Functions/BlobStorage.cs
- Functions/Hash.cs
- Functions/IStorageService.cs
- Functions/Range.cs
Copy of #35 
This PR adds tests and makes small refactors
> Add tests #2

- Functions/BlobStorageEntry.cs
- Functions/Program.cs
- Functions/Range.cs
Simplifying code by removing the possibility of `LastModified` being null when a hash file is found.
> Removing nullability possibilities.

- README.md
Instead of using the different GitHub Action badge style, I've updated the badges to conform to the style of the other badges on the README.
> Updated GitHub Actions badges to be consistent style with other badges

- Functions.Tests/Helpers/TestFunctionContext.cs
- Functions/Functions.csproj
- Functions/Program.cs
- Functions/Range.cs
- Functions/host.json
* Adding proper Application Insights telemetry
* Fixing a dependency injection bug
Closes #32
> AppInsights and DI bug fix.

- .github/workflows/deploy-function.yml
Adding a deployment script for automatic deployment to Azure.
> Adding deployment script.

- Functions.Tests/HaveIBeenPwned.PwnedPasswords.Tests.csproj
- Functions/Abstractions/IFileStorage.cs
- Functions/Abstractions/ITableStorage.cs
- Functions/Functions/Ingestion/ProcessTransaction.cs
- Functions/Functions/Ingestion/Submit.cs
- Functions/HaveIBeenPwned.PwnedPasswords.csproj
- Functions/HttpRequestDataExtensions.cs
- Functions/Implementations/Azure/BlobStorage.cs
- Functions/Implementations/Azure/TableStorage.cs
- Functions/Models/PwnedPasswordsIngestionValue.cs
- Functions/Startup.cs
- Ingestion.md
Updating NuGet packages.
JSON Schema changes.
Supporting bigger ingestion files.
Fixing Ingestion documentation.
> Miscellanous improvements after testing.

- Directory.Build.props
- Functions.Tests/HashTests.cs
- Functions.Tests/PwnedPasswordAppendTests.cs
- Functions.Tests/RangeTests.cs
- Functions/Abstractions/ICdnStorage.cs
- Functions/Abstractions/IFileStorage.cs
- Functions/Functions/Ingestion/Submit.cs
- Functions/Functions/Range.cs
- Functions/Hash.cs
- Functions/HaveIBeenPwned.PwnedPasswords.csproj
- Functions/HttpRequestDataExtensions.cs
- Functions/Implementations/Azure/QueueStorage.cs
- Functions/Implementations/Azure/TableStorage.cs
- HaveIBeenPwned.PwnedPasswords.Core/HaveIBeenPwned.PwnedPasswords.Core.csproj
- PwnedPasswords.sln
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/Hash.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/HaveIBeenPwned.PwnedPasswords.Shared.csproj
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/MD4.cs
- Tools/PwnedPasswords-Prepare/Program.cs
- Tools/PwnedPasswords-Prepare/PwnedPasswords-Prepare.csproj
* Code cleanups and documentation
* Adding a core library for shared functionality and a command-line tool to prepare password files for ingestion.
* Updating NuGet packages.
> Miscellaneous fixes and improvements

- Functions/Implementations/Azure/BlobStorage.cs
Fixing performance regression in Range-GET
> Fixing performance regression in Range.

- .github/workflows/deploy-function.yml
The deployment process was also building the test project and other things. Limiting it to only build the functions.
> Fixing the deployment process to only build the Function project.

- Functions.Tests/RangeTests.cs
- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Range.cs
- Functions/Implementations/Azure/BlobStorage.cs
- Functions/Models/PwnedPasswordsFile.cs
Now reading the entire blob before serving it out to the response.
> More performance optimizations

- Functions.Tests/RangeTests.cs
- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Range.cs
- Functions/HaveIBeenPwned.PwnedPasswords.csproj
- Functions/Implementations/Azure/BlobStorage.cs
- Functions/Models/PwnedPasswordsFile.cs
Trying to fix perf issues by using recyclable memory streams to keep GC pressure to a minimum
> Trying recyclablestreams to fix perf issues.

- Functions/Implementations/Cloudflare/CdnStorage.cs
Adding logging for URIs that are being purged from Cloudflare Cache.
> Logging which URIs are being purged from cache.

- Functions/host.json
> Increasing the max-duration to 10 minutes.

- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Ingestion/ProcessTransaction.cs
- Functions/Implementations/Cloudflare/CdnStorage.cs
- Functions/Startup.cs
Reducing parallelism from 16 tasks to 4 to prevent exhaustion.
> Reducing parallelism to 4

- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Ingestion/ProcessTransaction.cs
- Functions/Implementations/Cloudflare/CdnStorage.cs
> Ignoring cancellation tokens for some operations.

- Functions/host.json
Changing host max-runtime to 30 minutes.
> Changing max host duration to 30 minutes.

- Functions/Functions/Ingestion/ProcessTransaction.cs
> Fixing dictionary access in batching logic.

- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
Moving stuff out of loop to prevent unnecessary dependency calls.
> Fixing logic error in batching

- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
Updating tables and blobs in parallel while processing batches.
> Doing more stuff in parallel while processing batches.

- Functions/Abstractions/ITableStorage.cs
- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Ingestion/ProcessTransaction.cs
- Functions/Implementations/Azure/QueueStorage.cs
- Functions/Implementations/Azure/TableStorage.cs
- Functions/Models/QueuePasswordEntry.cs
Making the batches bigger to speed up processing even more.
> Making the batches bigger.

- Functions.Tests/RangeTests.cs
- Functions/Abstractions/IFileStorage.cs
- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Range.cs
- Functions/Implementations/Azure/BlobStorage.cs
First update for NTLM support.
> WIP: Adding rudimentary support for ntlm.

- Functions.Tests/HashEntryTests.cs
- Functions.Tests/HashTests.cs
- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Ingestion/ProcessTransaction.cs
- Functions/Functions/Range.cs
- Functions/HaveIBeenPwned.PwnedPasswords.csproj
- Functions/Implementations/Azure/BlobStorage.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/Hash.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/HashEntry.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/HaveIBeenPwned.PwnedPasswords.Shared.csproj
- Tools/PwnedPasswords-IngestionPatcher/Program.cs
- Tools/PwnedPasswords-Prepare/Program.cs
- Tools/PwnedPasswords-Splitter/Program.cs
> Code cleanups

- Functions.Tests/RangeTests.cs
- Functions/Functions/Range.cs
Returning explicit HttpResponseMessage object in an attempt to fix missing Content-Length headers.
> Attempting to fix Content-Length issues.

- Functions.Tests/RangeTests.cs
- Functions/Functions/Range.cs
Another Content-Length fix attempt.
> Another content-length fix attempt.

- Functions.Tests/RangeTests.cs
> Fixing test

- Functions/Functions/Range.cs
Precompressing data to try to maintain Content-Length
> Precompressing for Content-Length

- .github/workflows/ci-build.yml
- Functions.Tests/HashEntryTests.cs
- Functions.Tests/RangeTests.cs
- Functions/Abstractions/IFileStorage.cs
- Functions/Abstractions/ITableStorage.cs
- Functions/Functions/Ingestion/ProcessPwnedPasswordEntry.cs
- Functions/Functions/Ingestion/ProcessTransaction.cs
- Functions/Functions/Range.cs
- Functions/HaveIBeenPwned.PwnedPasswords.csproj
- Functions/Implementations/Azure/BlobStorage.cs
- Functions/Implementations/Azure/QueueStorage.cs
- Functions/Implementations/Azure/TableStorage.cs
- Functions/Models/QueuePasswordEntry.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/HashEntry.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/HashType.cs
- Shared/HaveIBeenPwned.PwnedPasswords.Shared/HaveIBeenPwned.PwnedPasswords.Shared.csproj
- Tools/PwnedPasswords-IngestionPatcher/Program.cs
- Tools/PwnedPasswords-IngestionPatcher/PwnedPasswords-IngestionPatcher.csproj
* Adding support for NTLM hashes during ingestion
* Code Cleanups
> Adding support for NTLM hashes during ingestion
